### ISSUE TITLE
Space Travelers: Set-up Kanban board

### ISSUE THREAD

**Issue by Leboroz** [Leboroz/space-travelers#25]
## We are a team of 2 exceptional developers:

- @Leboroz 
- @Bondok6 

![hello](https://media.tenor.co/images/acc4116372dcc4b342cb1a00ae657151/tenor.gif)

[Link to the repo](https://github.com/Leboroz/space-travelers)
[Link to the project](https://github.com/Leboroz/space-travelers/projects/1)

**Comment by rustam-tolipov** [comment]
## HELLO TEAM 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
